# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b24a2f82f165f7f48b935bed3323da55c867a78c8191d21e2e34193b05631a33425f77795ff8a27fb0dff68a6590d0dfc18613f85f759622ef8afc86a7d7a12

test:
  secret_key_base: 93797f98339035886c49bbcd1c330f8a076ab699e7fc5c2ececb86b57421ad0997dc237016b1471554047d17d02f95b17a7d48903eb0d24b7d018227976131f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
